### ISSUE TITLE
[Bug] Bonus Names

### ISSUE THREAD

**Issue by stunslave** [surftimer/SurfTimer-discord#1]
The bug is rather explanatory, shows in the image that if there are more than 1 bonus on a map. 
The first bonus on a map is announced as **"New Bonus 0 World Record"** In which it should be _"New Bonus 1 World Record"._

![image](https://user-images.githubusercontent.com/47533535/121307692-8ac0b480-c900-11eb-9444-52cd1f0950bc.png)

____________
On another note can per bonus images added.. :) thanks
Currently all my bonus images are named surf_mapname_b1 | surf_mapname_b2 | surf_mapname_b3 etc

**Comment by Sarrus1** [comment]
Thanks for reporting this.
I think bonuses are indexed starting at 0 so I'll add a simple +1 offset to fix that.

Regarding the bonus images, this line adds the bonus number to the url:
https://github.com/Sarrus1/SurfTimer-discord/blob/888b8f71a0d7a68ed61c705310a0abdee75824ff/scripting/SurfTimer-discord.sp#L423
Did you enable the cvar for it?
It should be `sm_surftimer_discord_bonus_image  1`
I'll make it default I think.

**Comment by stunslave** [comment]
I was running the release version 1.0 which doesn't include bonus records etc. 
![image](https://user-images.githubusercontent.com/47533535/121478967-dc814180-c9c9-11eb-9131-0ebf3c923c66.png)
The bonus 0 bug is still here, so it wasn't a version issue.

I'm running the repo zip now, that has everything shot.

**Comment by stunslave** [comment]
Bonus Names.

`zonegroup` is this issue, older zones start from `zonegroup` "0" , newer start from "1".

Bonus 2 is always `zonegroup` "2". Bonus 3 is always `zonegroup` "3". etc
So changing `zonegroup` "0" to "1" in the DB fixes the issue on discord.

**Comment by Sarrus1** [comment]
I see so by default there is no bonus 1 right it's always 0? Then it goes normally 2,3,4...

**Comment by stunslave** [comment]
Not always 0.. Sometimes it's 1.. I don't know why. 
Above fix didn't work :>

**Comment by stunslave** [comment]
It seems like enabling bonus causes all types of shit lol
Top record is Map Record - Shows Bonus 0
Next 2 records are from the test which seem to work.

![image](https://user-images.githubusercontent.com/47533535/121561677-057cf300-ca19-11eb-8d2c-f06249b829d7.png)

I cant re-open this [bug] :>

Edit: 
Jumped back to the version without bonus images.. Works again.

**Comment by Sarrus1** [comment]
This should be fixed in 9be27091a12ba573a773744c103a4c29264d7bd6
**YOU HAVE TO COMPILE IT YOURSELF, THE BINARIES ARE NOT UPDATED**

**Comment by stunslave** [comment]
I always compile I don't trust precompiled shit lol.
Nope that didnt fix it lol. Turned bonus 1 into Bonus 2.

![image](https://user-images.githubusercontent.com/47533535/121643549-3baa8900-ca92-11eb-9c75-53eed8dabae6.png)
Image/Record 1 = 1 Bonus on Map (Shows Bonus 2)
Image/Record 2 = 1 Bonus on Map (Shows Bonus 2)
Image/Record 3 = 3 Bonuses on Map (Bonus 1 completed - shows Bonus 2)

![image](https://user-images.githubusercontent.com/47533535/121644936-ea9b9480-ca93-11eb-8daa-d972cab775d5.png)
![image](https://user-images.githubusercontent.com/47533535/121645053-0ef77100-ca94-11eb-9a0f-8c25b953f5c4.png)
This last image is the Main Map Completion on surf_1day - Shows Bonus 1 Record...

Seems like the main map is taking the spot of bonus 1.. (maybe lol)
Need more people to test it.

**Comment by stunslave** [comment]
I have reverted back to the old Surftimer / Discord announcements. 
When it's working I'll add it again.
